spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/azhost}
    username: ${DATABASE_USERNAME:azhost_user}
    password: ${DATABASE_PASSWORD:azhost_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    com.azhost: DEBUG
